tools/importer/inventory.json

Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.page/en
- After: https://block-rename-test--fondationsaudemarspiguet--aemdemos.aem.page/en

Block rename test

---

styles/styles.css

Fix #33 
Test URLs:
- After: https://issue-33--fondationsaudemarspiguet--aemdemos.aem.live/

feat: original site colors import

---

tools/importer/inventory.json

Test URLs:
- After: https://rename-blocks--fondationsaudemarspiguet--aemdemos.aem.live/

Update inventory.json for renaming columns (columns26) -> carousel (vertical)

---

tools/importer/inventory.json

Fix #<gh-issue-id>
Test URLs:
- After: https://icon-grid--fondationsaudemarspiguet--aemdemos.aem.live/

icon-grid commit1

---

blocks/map/infobox.js
blocks/map/initmapscript.js
blocks/map/map.css
blocks/map/map.js
blocks/map/mapstyles.js
blocks/map/markerclusterer.js

Fix #<gh-issue-id>
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.page/en/fondation-pour-les-arbres-projects-map
- After: https://mapv2--fondationsaudemarspiguet--aemdemos.aem.page/en/fondation-pour-les-arbres-projects-map

Fixing map

---

helix-query.yaml

Fix #74 
Test URLs:
- After: https://issue74--fondationsaudemarspiguet--aemdemos.aem.live/

Updating helix query for adding news en and news fr indexes

---

blocks/header/header.css
blocks/header/header.js

Fix #80 
Test URLs:
- After: https://80-headerfix--fondationsaudemarspiguet--aemdemos.aem.page/
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-the-foundation-our-partners
- After: https://80-headerfix--fondationsaudemarspiguet--aemdemos.aem.page/en/fondation-pour-les-arbres-the-foundation-our-partners

fixed scrolling and url based menu color

---

blocks/footer/footer.js
blocks/header/header.css
blocks/header/header.js
scripts/languages.js
scripts/scripts.js
styles/styles.css

Fix #87 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en
- After: https://language-switcher--fondationsaudemarspiguet--aemdemos.aem.live/en
Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/cookie-policy
after: https://language-switcher--fondationsaudemarspiguet--aemdemos.aem.live/en/cookie-policy
This PR also covers h2 transition and default page styles

feat: Language switcher

---

blocks/articleintro/articleintro.css
blocks/articleintro/articleintro.js
blocks/header/header.css
blocks/header/header.js
scripts/utils.js
templates/news-article/news-article.css
templates/news-article/news-article.js

Fix #117 
Test URLs:
- After: https://issue117--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-news/education-and-resilience-future-proofing-the-youth-of-uganda

Header animation on scrolling along with decorating section just below ArticleIntro block

---

scripts/ffetch.js

Fix #136 
Test URLs:
- After: https://issue136--fondationsaudemarspiguet--aemdemos.aem.live/

Adding logic of ffetch

---

blocks/articlecontent/articlecontent.css
blocks/featured-projects/featured-projects.css
blocks/featured-projects/featured-projects.js
helix-query.yaml

Fix #67 
Test URLs:
- After: https://issue67-dynamic--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-news/education-and-resilience-future-proofing-the-youth-of-uganda
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-projects/creating-a-forest-for-learning-iii
- After: https://issue67-dynamic--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-projects/creating-a-forest-for-learning-iii

Implementation of Dynamic Ribbon for both News & Projects articles

---

blocks/header/header.js

Fix #157 
Test URLs:
- After: https://issue157--fondationsaudemarspiguet--aemdemos.aem.live/

Fixing bug

---

tools/importer/import.utils.js
tools/importer/importnews.js
tools/importer/inventory.json
tools/importer/parsers/removecontent.js
tools/importer/parsers/sectionmetadata.js

Fix #167 
Test URLs:
- After: https://issue167--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-news/education-and-resilience-future-proofing-the-youth-of-uganda

Enabling Importer to deal with everything for Importing News Articles as per the AEMY standards

---

blocks/hero/hero.js

Fix #160 
Test URLs:
- After: https://hero-video2--fondationsaudemarspiguet--aemdemos.aem.page/

Hero Video is not coming on the .live page

---

blocks/quote/quote.css

Fix #127
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-the-foundation-our-mission
- After: https://127-quote-similar-style--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-the-foundation-our-mission

127-quote-no-quoter commit1

---

templates/news-article/news-article.css
templates/news-article/news-article.js

Fix #159 
Test URLs:
- After: https://issue-159--fondationsaudemarspiguet--aemdemos.aem.page/en/fondation-pour-les-arbres-news/education-and-resilience-future-proofing-the-youth-of-uganda

[News Article] Fix news details section

---

templates/news-article/news-article.css

Test URLs:
- After: https://newsfix--fondationsaudemarspiguet--aemdemos.aem.page/en/fondation-pour-les-arbres-news/education-and-resilience-future-proofing-the-youth-of-uganda

New Detail Fix

---

blocks/featured-projects/featured-projects.css
blocks/featured-projects/featured-projects.js
templates/news-article/news-article.css
templates/news-article/news-article.js

Fix #175 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-news/new-forest-reserve-in-the-parc-naturel-du-jorat
- After: https://issue175v1--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-news/new-forest-reserve-in-the-parc-naturel-du-jorat

Fixing CSS issues on the News Pages

---

blocks/carousel/carousel.css
blocks/carousel/carousel.js

Fix #196 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/fr/fondation-pour-les-arbres-nos-projets/agroforesterie-et-entrepreneuriat-vert
- After: https://197-carousel-background--fondationsaudemarspiguet--aemdemos.aem.live/fr/fondation-pour-les-arbres-nos-projets/agroforesterie-et-entrepreneuriat-vert

197-carousel-background commit1

---

templates/news-article/news-article.css

Fix #189 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-news/on-the-trail-of-resonance-wood
- After: https://issue189v1--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-news/on-the-trail-of-resonance-wood

Fixing the CSS

---

blocks/featured-projects/featured-projects.css
templates/news-article/news-article.css

Fix #196 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-projects/awareness-raising-and-environmental-education-for-young-peop
- After: https://issue196v2--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-projects/awareness-raising-and-environmental-education-for-young-peop

Fixing the background

---

blocks/hero/hero.css

Fix #194 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-projects/awareness-raising-and-environmental-education-for-young-peop
- After: https://194-hero-two-columnar-bug--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-projects/awareness-raising-and-environmental-education-for-young-peop

194-hero-two-columnar-bug commit1

---

blocks/columns/columns.css

Fix #208 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/media-newsroom
- After: https://issue-208--fondationsaudemarspiguet--aemdemos.aem.page/en/media-newsroom

changed to specific columns(buttons) variant

---

blocks/hero/hero.css

Fix #187 
Test URLs:
- After: https://hero-video2--fondationsaudemarspiguet--aemdemos.aem.page/

[Hero Video - Mobile View] - text placement not same as on original

---

helix-query.yaml

Fix #223 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/query-index.json
- After: https://fix-index--fondationsaudemarspiguet--aemdemos.aem.live/query-index.json

fix: index to include news and project pages

---

blocks/featured-projects/featured-projects.js

Fix #206 
Test URLs:
- After: https://issue206-v2--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-news/education-and-resilience-future-proofing-the-youth-of-uganda

Enabling Categories logic further to be instrumented on News pages versus Project Pages

---

blocks/hero/hero.css

Fix #210 
Test URLs:
Hero (video)
- After: https://issue-210--fondationsaudemarspiguet--aemdemos.aem.live/
Hero (two-columnar-text-image)
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-projects/support-programme-for-biodiversity-ngos-working-in-developin
- After: https://issue-210--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-projects/support-programme-for-biodiversity-ngos-working-in-developin
Hero (two-columnar)
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les …

chore: update vh to metric adaptable to iframe

---

templates/news-landing/news-landing.js
templates/projects-landing/projects-landing.js

Fix #236 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-news
- After: https://issue236--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-news

Landing pages Implementation Rollout Begins

---

styles/styles.css

Fix #250 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/fr/credits-photographiques
- After: https://issue-250--fondationsaudemarspiguet--aemdemos.aem.live/fr/credits-photographiques
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/credits-photographiques
- After: https://issue-250--fondationsaudemarspiguet--aemdemos.aem.live/en/credits-photographiques

feat: style credits page

---

helix-query.yaml

Fix #279 
Test URLs:
- After: https://issue279--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/

Adding article-color to helix yaml

---

helix-query.yaml

Fix #281 
Test URLs:
- After: https://issue281--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/

Fixing helix yaml

---

templates/news-landing/news-landing.css
templates/news-landing/news-landing.js

Fix #171 
Test URLs:
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.page/en/fondation-pour-les-arbres-news
- After: https://issue-171--arbres-fondationsaudemarspiguet--audemars-piguet.aem.page/en/fondation-pour-les-arbres-news

Phase1- Logic for searching, sorting, clear search, category wise filter on news landing page

---

blocks/map/initmapscript.js

Fix #315 
Test URLs:
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects-map
- After: https://issue315v1--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects-map
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/fr/fondation-pour-les-arbres-nos-projets-carte
- After: https://issue315v1--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/fr/fondation-pour-les-arbres-nos-projets-carte

Change of DA location for Maps

---

helix-query.yaml

Fix #329
Test URLs:
- After: https://issue329--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/

Enabling homepage as metadata

---

helix-query.yaml

Fix #333 
Test URLs:
- After: https://issue333--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/

Enabling Projects home page logic

---

helix-query.yaml

Fix #335 
Test URLs:
- After: https://issue335--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/

Enabling Projects home page metadata logic

---

helix-query.yaml

Fix #342 
Test URLs:
- After: https://issue342--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/

Enabling featured metadata

---

styles/styles.css

Fix #310 
Test URLs:
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-the-foundation-our-team
https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/fr/fondation-pour-les-arbres-la-fondation-notre-equipe
- After: https://issue-310--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-the-foundation-our-team
- https://issue-310--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/fr/fondation-pour-les-arbres-la-fondation-notre-equipe

Teams page Styling

---

scripts/scripts.js
styles/styles.css

Fix #173 
Test URLs:
- After: https://issue173v1--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/

Fixing bug for left to right via Web Animations API

---

blocks/cards/cards.js

Fix #349 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-the-foundation-our-mission
- After: https://issue-349--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-the-foundation-our-mission

fix(icons-grid): vertical scroll in carousel view

---

404.html
scripts/scripts.js

Fix #351 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/fr/fondation-pour-les-arbres-news1
- After: https://issue-351--fondationsaudemarspiguet--aemdemos.aem.live/fr/fondation-pour-les-arbres-news1
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-projects1
- After: https://issue-351--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-les-arbres-projects1
Original site References for en and fr versions: 
https://arbres.fondationsaudemarspiguet.org/en/fondation-pour-les-arbres-projects1
https://arbres.fondationsaudemarspiguet.org/fr/fondation-pour-les-arbres …

feat: 404 page

---

blocks/news-slider/news-slider.css

Fix #378 
Test URLs:
- After: https://issue378--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/

Fixing CSS bug

---

styles/styles.css

Fix #393 
Test URLs:
- Before: https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/en/fondation-pour-le-bien-commun-the-foundation-our-team
- https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/en/privacy-notice
- https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/en/terms-of-use
- https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/fr/conditions-dutilisation
- https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/fr/declaration-de-confidentialite
- https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/fr/fo …

color changes to privacy-notice/teams page/terms-of-use/ section border

---

blocks/featured-projects/featured-projects.css
blocks/featured-projects/featured-projects.js
templates/project-article/project-article.css

Fix #388 
Test URLs:
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects/stepping-up-protection-for-a-thousand-hectares-of-forest-fra
- After: https://issue388--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects/stepping-up-protection-for-a-thousand-hectares-of-forest-fra

Adding logic for 2 cards between a certain viewport - 600 & 900

---

blocks/featured-projects/featured-projects.css
blocks/hero/hero.css
styles/styles.css
templates/project-article/project-article.css

Fix #405 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-le-bien-commun-projects/a-10-increase-in-the-distribution-of-hot-meals-to-the-most-d
- After: https://issue-405--fondationsaudemarspiguet--aemdemos.aem.live/en/fondation-pour-le-bien-commun-projects/a-10-increase-in-the-distribution-of-hot-meals-to-the-most-d
- Before: https://main--fondationsaudemarspiguet--aemdemos.aem.live/fr/fondation-pour-le-bien-commun-nos-projets/augmentation-de-10-de-la-distribution-de-repas-chauds-aux-pl
- After: https://issue-405--fondationsaudemarspiguet--aemdemos.aem.live/fr/fondation-pour-le-bien-commun-nos-proj …

feat: biencommun project pages styles

---

templates/projects-landing/projects-landing.js

Fix #427  
Test URLs:
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/fr/fondation-pour-les-arbres-nos-projets
- After: https://issue-427--arbres-fondationsaudemarspiguet--audemars-piguet.aem.page/fr/fondation-pour-les-arbres-nos-projets
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects
- After: https://issue-427--arbres-fondationsaudemarspiguet--audemars-piguet.aem.page/en/fondation-pour-les-arbres-projects

project articles filtered based on path

---

blocks/cards/cards.css
blocks/cards/cards.js
styles/styles.css

Fix #426
Test URLs:
Biencommun
English
Before: https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/en
After: https://bstats--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/en
French
Before: https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/fr
After: https://bstats--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/fr
Abres
English
Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en
After: https://bstats--arbres-fondationsaudemarspiguet--audemars-piguet.aem.page/en
French
Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/fr/
After: https://bstats--arbres-fondationsaudemarspiguet--audemars-piguet.aem.page/fr

[Biencommun Site] Style icons-grid statistics block

---

blocks/home-projects/home-projects.css
blocks/home-projects/home-projects.js
blocks/news-slider/news-slider.js

Fix #444 
Test URLs:
- Before: https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/
- After: https://issuebihp--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/

Adding JS logic for news slider & Projects section hp

---

templates/news-landing/news-landing.js
templates/projects-landing/projects-landing.js

Fix #442 
Test URLs:
Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-news
After: https://issue-442--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-news
Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/fr/fondation-pour-les-arbres-actualites
After: https://issue-442--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/fr/fondation-pour-les-arbres-actualites
Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects
After: https://issue-442--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects
Before: …

Project Landing and News Landing  for biencommun

---

blocks/carousel/carousel.css
blocks/news-slider/news-slider.css
blocks/table/table.css
blocks/table/table.js

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after)
Test URLs:
- After: https://misc--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/

Media newsroom table / teams table / news slider icons / biencommun hero carousel

---

templates/news-landing/news-landing.css
templates/news-landing/news-landing.js
templates/projects-landing/projects-landing.css
templates/projects-landing/projects-landing.js

Fix #449 
Test URLs:
Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-news
After: https://issue-449--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-news
Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/fr/fondation-pour-les-arbres-actualites
After: https://issue-449--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/fr/fondation-pour-les-arbres-actualites
Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects
After: https://issue-449--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects
Before: …

filtered news and projects articles based on path

---

scripts/scripts.js
styles/styles.css

Fix #456 
Test URLs:
- After: https://issue-456--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/

full-width changes restricted to contact us page only 

---

styles/styles.css

Fix #464 
Test URLs:
- Before: https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/en/terms-of-use
- After: https://issue-464--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/en/terms-of-use

color change in terms-of-use(contact us)

---

styles/styles.css

Fix #448
 
**English** 
Before: https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/
After: https://colortext--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/
**French** 
Before: https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/fr
After: https://colortext--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/fr
 
**English** 
Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/
After: https://colortext--arbres-fondationsaudemarspiguet--audemars-piguet.aem.page/
**French** 
Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/fr
After: https://colortext--arbres-fondationsaudemarspiguet--audemars-piguet.aem.page/fr

[Biencommun] Colored-text

---

styles/styles.css

Fix #474 
Test URLs:
- Before: https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-le-bien-commun-the-foundation-our-team
- After: https://issue-474--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-le-bien-commun-the-foundation-our-team

removes color dependency of cream-bg

---

blocks/columns/columns.css
blocks/table/table.css
styles/styles.css
templates/newsroom/newsroom.css

Fix #497 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--audemars-piguet.aem.live/fr/espace-medias
- After: https://issue-497--fondationsaudemarspiguet--audemars-piguet.aem.live/fr/espace-medias
https://issue-497--fondationsaudemarspiguet--audemars-piguet.aem.live/en/media-newsroom

[Fondations] Media Newsroom

---

blocks/articleintro/articleintro.css
blocks/articleintro/articleintro.js
blocks/quote/quote.css
scripts/utils.js
styles/styles.css

Fix #503 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--audemars-piguet.aem.page/en/audemars-piguet-foundations-6
- After: https://issue503--fondationsaudemarspiguet--audemars-piguet.aem.page/en/audemars-piguet-foundations-6
- Before: https://main--fondationsaudemarspiguet--audemars-piguet.aem.page/fr/page-fondations-audemars-piguet
- After: https://issue503--fondationsaudemarspiguet--audemars-piguet.aem.page/fr/page-fondations-audemars-piguet

Instrumentation of fondations audemars-piguet-foundations-6 page - both en and fr

---

templates/news-landing/news-landing.js

Fix #515 
Test URLs:
-Before: https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-le-bien-commun-news
- After: https://issue-515--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-le-bien-commun-news

short description fix for longer descriptions

---

styles/styles.css

Fix #524 
Test URLs:
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.page/en/fondation-pour-les-arbres-contact
- After: https://issue-524--arbres-fondationsaudemarspiguet--audemars-piguet.aem.page/en/fondation-pour-les-arbres-contact

removing b tag from styles.css

---

blocks/carousel/carousel.css
blocks/carousel/carousel.js

Fix #513 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--audemars-piguet.aem.live/drafts/rusmeen/
- After: https://issue-513--fondationsaudemarspiguet--audemars-piguet.aem.live/drafts/rusmeen/

fixed alignment of content for fondations carousel and buttons working

---

blocks/carousel/carousel.css

Fix #526 
Test URLs: 
- Before: https://main--fondationsaudemarspiguet--audemars-piguet.aem.live/
- After: https://issue-526--fondationsaudemarspiguet--audemars-piguet.aem.live/
- After: https://issue-526--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/
- Before: https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/en/our-mission
- After: https://issue-526--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/en/our-mission
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondati …

fixed margin above about button & carousel indicators z-index

---

styles/styles.css

Fix #532 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--audemars-piguet.aem.live/en/audemars-piguet-foundations-6
- After: https://issue532--fondationsaudemarspiguet--audemars-piguet.aem.live/en/audemars-piguet-foundations-6

Maintaining consistency across bg color names

---

blocks/carousel/carousel.css

Fix #514 
Test URLs:
- After: https://issue-514--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/

Testing live preview feature 

---

blocks/header/header.js

Fix #517 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--audemars-piguet.aem.page/en/contact
- After: https://issue-517--fondationsaudemarspiguet--audemars-piguet.aem.page/en/contact

Disabling scroll limit for short content

---

styles/styles.css

Fix #544 
Test URLs:
- Before:  https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/en/fondation-pour-le-bien-commun-projects
- After: https://i544--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/en/fondation-pour-le-bien-commun-projects

margin fix

---

styles/styles.css

Fix #549 
Test URLs:
- After: https://issue-549--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/

adding colors to main(styles.css)

---

blocks/featured-projects/featured-projects.css

Fix #555 
Test URLs:
- Before: https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/en/fondation-pour-le-bien-commun-projects/transfaire-tomorrow-a-job-for-everyone
- After: https://issue-555--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.page/en/fondation-pour-le-bien-commun-projects/transfaire-tomorrow-a-job-for-everyone

adding biencommun colors to projects ribbon

---

styles/styles.css

Fix #556 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--audemars-piguet.aem.page/fr/contact
- After: https://issue-556--fondationsaudemarspiguet--audemars-piguet.aem.page/fr/contact
https://issue-556--fondationsaudemarspiguet--audemars-piguet.aem.page/en/contact

Remove the padding below picture in contact-us page

---

blocks/carousel/carousel.css

Fix #561 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--audemars-piguet.aem.live
- After: https://issue-561--fondationsaudemarspiguet--audemars-piguet.aem.live

social icon & bg color of button fixed

---

blocks/carousel/carousel.css
blocks/carousel/carousel.js
blocks/columns/columns.css

Fix #<gh-issue-id>
Test URLs:
- After: https://issue-574--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-the-foundation-our-mission
- After: https://issue-574--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-the-foundation-our-mission
- Before: https://main--fondationsaudemarspiguet--audemars-piguet.aem.live/
- After: https://issue-574--fondationsaudemarspiguet--audemars-piguet.aem.live/

createOptimise function added for all carousels

---

styles/styles.css
templates/news-article/news-article.css
templates/project-article/project-article.css

Fix #580 
Test URLs:
- Before: https://main--fondationsaudemarspiguet--audemars-piguet.aem.live
- After: https://issue-580--fondationsaudemarspiguet--audemars-piguet.aem.live
- After: https://issue-580--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/

fixed styling of h1 & height of carousel fixed

---

blocks/hero/hero.js
templates/projects-landing/projects-landing.css

Fix #598 
Test URLs:
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects
- After: https://issue598--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects
Home Page
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en
- After: https://issue598--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en
Mission Page
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-the-foundation-our-mission
- After: https://issue598--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-the-foundation-our-mission
History Page
- Before: …

[Project Landing] UAT Part 1 issues

---

scripts/scripts.js
styles/styles.css

Fix #603 
Test URLs:
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.page/en/fondation-pour-les-arbres-contact
- After: https://issue-603--arbres-fondationsaudemarspiguet--audemars-piguet.aem.page/en/fondation-pour-les-arbres-contact

fonts , spacing , padding on contact's page

---

blocks/hero/hero.css
styles/styles.css
templates/project-article/project-article.css
templates/project-article/project-article.js

Fix #604 
Test URLs:
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects/support-programme-for-biodiversity-ngos-working-in-developin
- After: https://issue604--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects/support-programme-for-biodiversity-ngos-working-in-developin
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en/fondation-pour-les-arbres-projects/stepping-up-protection-for-a-thousand-hectares-of-forest-fra
- After: https://issue604--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/en …

chore(project article): fonts/alignments/typos

---

blocks/carousel/carousel.css
blocks/hero/hero.css
scripts/scripts.js

Fix #612 
Test URLs:
- After: https://issue-612--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/
- After: https://issue-612--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/
- Before: https://main--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/fr
- After: https://issue-612--biencommun-fondationsaudemarspiguet--audemars-piguet.aem.live/fr
- Before: https://main--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/fr
- After: https://issue-612--arbres-fondationsaudemarspiguet--audemars-piguet.aem.live/fr

added code for hero-video or hero-banner to start from top
